# deploy-windows.ps1 — Windows 桌面客户端 (Tauri v2) 编译/打包
#
# 干什么:
#   1) 检查 Node.js / Rust / cargo / MSVC 工具链 / WebView2
#   2) 自动写 windows\.env (从 .env.example 或参数生成)
#   3) cd web && npm install (首次)
#   4) cd windows && npm install (首次)
#   5) npm run tauri:build  → 产出 .msi / .exe
#
# 用法:
#   # 完整打包 (生成 msi/nsis 安装包)
#   powershell -ExecutionPolicy Bypass -File scripts-deploy\deploy-windows.ps1
#
#   # 指定后端服务器地址 (会写进 .env, 烧到客户端里作为出厂默认地址)
#   powershell -ExecutionPolicy Bypass -File scripts-deploy\deploy-windows.ps1 `
#       -ServerUrl 'https://taskflow.example.com'
#
#   # 开发模式 (热重载, 不打包)
#   powershell -ExecutionPolicy Bypass -File scripts-deploy\deploy-windows.ps1 -Dev
#
#   # 跳过环境检查 (你确定环境 OK 就用这个加速)
#   powershell -ExecutionPolicy Bypass -File scripts-deploy\deploy-windows.ps1 -SkipChecks
#
# 产物:
#   windows\src-tauri\target\release\bundle\msi\*.msi
#   windows\src-tauri\target\release\bundle\nsis\*-setup.exe
#
# 报错排查 (按出现频率排序):
#   - link.exe not found / MSVC error → 没装 VS Build Tools
#       → 装 https://visualstudio.microsoft.com/visual-cpp-build-tools/
#         勾选 "Desktop development with C++" 工作负载
#   - error: linker `link.exe` not found → 同上
#   - WebView2 相关报错 → tauri.conf.json 里 webviewInstallMode=downloadBootstrapper
#         意味着安装包里不带 WebView2, 用户首次启动会自动下载. 一般不用管.
#   - cargo download 慢 → 设国内镜像:
#         参考 https://mirrors.tuna.tsinghua.edu.cn/help/crates.io-index/
#   - Rust 编译报 "could not find Cargo.toml" → 路径错了, 必须从 windows 目录跑
#   - "Failed to resolve import" / 白屏 → vite.config.ts 里 base 必须是 './'
#   - 安装后闪退 → 看 %APPDATA%\TaskFlow\fatal.log

[CmdletBinding()]
param(
    [string]$ServerUrl,
    [switch]$Dev,
    [switch]$SkipChecks,
    [switch]$Release,           # 默认就是 release, 这个开关只是显式标识
    [switch]$Debug              # cargo build 不开优化, 编译快但产物大
)

$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot '_common.ps1')

Show-Diagnostic

$winDir = Join-Path $script:RepoRoot 'windows'
$webDir = Join-Path $script:RepoRoot 'web'

if (-not (Test-Path $winDir)) {
    Write-Fail "找不到 windows 目录: $winDir" '请确认你在 TaskFlow 仓库根目录'
}

# ====== 1. 环境检查 ======
if (-not $SkipChecks) {
    Write-Step "检查环境依赖"

    Test-Command -Name 'node' -VersionArg '--version' `
        -InstallHint '装 Node.js 20+ : https://nodejs.org/zh-cn/download/'
    Test-Command -Name 'npm' -VersionArg '--version'

    Test-Command -Name 'cargo' -VersionArg '--version' `
        -InstallHint '装 Rust : https://rustup.rs/  (Windows 上一路回车默认 stable-x86_64-pc-windows-msvc)'
    Test-Command -Name 'rustc' -VersionArg '--version'

    # 检查 Rust 工具链是不是 MSVC 版本 (gnu 版会找不到 link.exe)
    $rustcInfo = & rustc -vV 2>&1 | Out-String
    if ($rustcInfo -notmatch 'host:.*pc-windows-msvc') {
        Write-Warn2 "rustc 不是 msvc 工具链, Tauri 在 Windows 上需要 msvc"
        Write-Warn2 "建议执行: rustup default stable-x86_64-pc-windows-msvc"
    }

    # 检查 link.exe (MSVC linker)
    $vsWhere = Join-Path ${env:ProgramFiles(x86)} 'Microsoft Visual Studio\Installer\vswhere.exe'
    $hasLink = $false
    if (Test-Path $vsWhere) {
        $vsPath = & $vsWhere -latest -property installationPath 2>$null
        if ($vsPath) {
            Write-Ok "VS 安装路径: $vsPath"
            $hasLink = $true
        }
    }
    # 兜底直接搜 link.exe
    if (-not $hasLink) {
        $linkExe = Get-Command link.exe -ErrorAction SilentlyContinue
        if ($linkExe) {
            Write-Ok "link.exe: $($linkExe.Source)"
            $hasLink = $true
        }
    }
    if (-not $hasLink) {
        Write-Warn2 "未确认 MSVC 工具链 (link.exe). 第一次 cargo build 会失败的话:"
        Write-Warn2 "  -> 装 VS Build Tools: https://visualstudio.microsoft.com/visual-cpp-build-tools/"
        Write-Warn2 "  -> 勾选 'Desktop development with C++' 工作负载"
    }

    # 检查 WebView2
    $webview2Reg = 'HKLM:\SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}'
    if (Test-Path $webview2Reg) {
        $wvVer = (Get-ItemProperty $webview2Reg -ErrorAction SilentlyContinue).pv
        Write-Ok "WebView2 Runtime: $wvVer"
    } else {
        Write-Warn2 "未检测到 WebView2 Runtime. 不影响打包 (用户安装包会自动下载),"
        Write-Warn2 "但本机 tauri:dev 跑不起来. 装一下: https://developer.microsoft.com/microsoft-edge/webview2/"
    }
}

# ====== 2. 写 .env (定制出厂默认服务器地址) ======
Write-Step "准备 windows\.env"

$envFile = Join-Path $winDir '.env'
$envExample = Join-Path $winDir '.env.example'

if ($ServerUrl) {
    Write-Host "    > 用参数 -ServerUrl 写 .env: $ServerUrl"
    @"
# Auto-generated by deploy-windows.ps1
VITE_TASKFLOW_DEFAULT_SERVER=$ServerUrl
TASKFLOW_DEFAULT_SERVER_URL=$ServerUrl
"@ | Set-Content -Path $envFile -Encoding UTF8
    Write-Ok ".env 已写"
} elseif (Test-Path $envFile) {
    Write-Ok ".env 已存在, 不覆盖. 想重置就传 -ServerUrl 参数, 或手动删掉再跑"
    Import-DotEnv $envFile | Out-Null
} elseif (Test-Path $envExample) {
    Copy-Item $envExample $envFile
    Write-Warn2 "从 .env.example 复制 .env. 默认 server 地址可能不对!"
    Write-Warn2 "建议: 删掉 .env, 重跑脚本时加 -ServerUrl 'https://你的域名'"
    Import-DotEnv $envFile | Out-Null
} else {
    Write-Warn2 "没有 .env 也没有 .env.example. 客户端会用代码里的兜底地址 (http://localhost:8080)"
    Write-Warn2 "建议: -ServerUrl 'https://你的域名' 来定制"
}

# ====== 3. npm install ======
Write-Step "安装 web 依赖 (供 Tauri 复用)"
Push-Location $webDir
try {
    if (-not (Test-Path 'node_modules')) {
        Invoke-Native -Description 'npm install (web)' -Action {
            & npm install
        } -Hint '失败时设国内镜像: npm config set registry https://registry.npmmirror.com'
    } else {
        Write-Ok 'web/node_modules 已存在'
    }
} finally {
    Pop-Location
}

Write-Step "安装 windows 依赖 (Tauri CLI)"
Push-Location $winDir
try {
    if (-not (Test-Path 'node_modules')) {
        Invoke-Native -Description 'npm install (windows)' -Action {
            & npm install
        } -Hint '失败时设国内镜像: npm config set registry https://registry.npmmirror.com'
    } else {
        Write-Ok 'windows/node_modules 已存在'
    }
} finally {
    Pop-Location
}

# ====== 4. 构建 / Dev ======
Push-Location $winDir
try {
    if ($Dev) {
        Write-Step "启动 Tauri Dev (热重载, Ctrl+C 退出)"
        Write-Host "    > 这会同时启动 vite (1420) 和 Tauri 主程序窗口" -ForegroundColor DarkGray
        & npm run tauri:dev
        if ($LASTEXITCODE -ne 0) {
            Write-Fail "tauri:dev 退出 (code $LASTEXITCODE)" '看上方日志; 常见原因: WebView2 缺失, 或端口 1420 被占'
        }
    } else {
        Write-Step "Tauri 打包 (首次约 5-15 分钟, 之后 2-3 分钟)"
        Write-Host "    > 这一步会编译 Rust + 打 msi + 打 nsis exe" -ForegroundColor DarkGray

        if ($Debug) {
            $env:TAURI_ENV_DEBUG = '1'
            Write-Warn2 "Debug 模式: 产物大但编译快, 不要上传 Debug 产物给真实用户"
            Invoke-Native -Description 'tauri build --debug' -Action {
                & npm run tauri:build -- --debug
            }
            Remove-Item Env:TAURI_ENV_DEBUG -ErrorAction SilentlyContinue
        } else {
            Invoke-Native -Description 'tauri build (release)' -Action {
                & npm run tauri:build
            } -Hint @'
常见错误:
  * "linker `link.exe` not found"        → 装 VS Build Tools (Desktop dev with C++)
  * "could not find `Cargo.toml`"        → 必须在 windows 目录里跑
  * 下载 cargo crate 卡住                → 设清华源 https://mirrors.tuna.tsinghua.edu.cn/help/crates.io-index/
  * "Couldn't find ICO icon"             → src-tauri/icons/icon.ico 缺失, 见 README
'@
        }

        # 列出产物
        $bundleDir = Join-Path $winDir 'src-tauri\target\release\bundle'
        if ($Debug) {
            $bundleDir = Join-Path $winDir 'src-tauri\target\debug\bundle'
        }
        if (Test-Path $bundleDir) {
            Write-Host ""
            Write-Host "==> 打包完成, 产物:" -ForegroundColor Green
            Get-ChildItem -Path $bundleDir -Recurse -Include *.msi,*.exe |
                ForEach-Object {
                    $sizeMB = [math]::Round($_.Length / 1MB, 1)
                    Write-Host "    [$sizeMB MB] $($_.FullName)" -ForegroundColor Cyan
                }
        } else {
            Write-Fail "找不到 bundle 目录: $bundleDir" '打包可能失败, 翻上方日志'
        }
    }
} finally {
    Pop-Location
}

Write-Host ""
Write-Host "========================================" -ForegroundColor Green
Write-Host " Windows 客户端就绪" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Green
Write-Host " 把 .msi 或 setup.exe 上传到下载页, 用户安装即可."
Write-Host " 安装后闪退? 看 %APPDATA%\TaskFlow\fatal.log + taskflow.log"
Write-Host ""
